name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
      - name: Composer install (for indexing of vendor blade classes)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev
      - run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > public/version.json'
        shell: bash
      - name: Create tar
        run: tar -czf ct_bff_{{ env.RELEASE_VERSION }}.tar.gz ./app ./bootstrap ./config ./database ./public ./resources ./routes ./storage ./vendor ./composer.json
      - name: Upload release tar
        uses: actions/upload-artifact@v1
        with:
          name: ct_bff_{{ env.RELEASE_VERSION }}
          path: ct_bff_{{ env.RELEASE_VERSION }}.tar.gz
